apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: hatoon-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        envFrom:
        - secretRef:
            name: db-secrets
        ports:
        - containerPort: 3306
          name: mysql
