apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: hatoon-namespace
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        envFrom:
        - secretRef:
            name: db-secrets
        ports:
        - containerPort: 80
          name: wordpress
